on:
  push:
    branches:
      - master
  workflow_dispatch:
    
name: 🚀 Deploy bot to server
jobs:
  bot-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: ${{ secrets.ftp_port }}
        server-dir: ${{ secrets.bot_directory }}
    
    - name: ⚡ Restart server
      run: echo "Restart your server at ${{ secrets.bot_dashboard }}"
